# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: BeatCinema

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  main:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build windows
      - name: Zip files
        shell: pwsh
        run: |
          if ($env:RUNNER_OS -eq "Windows") {
            7z a BeatCinema.zip build\windows\x64\runner\Release\* -r
          }
          else {
            zip -r BeatCinema.zip build\windows\x64\runner\Release\*
          }
      # - name: Artifact
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: BeatCinema
      #     path: build\windows\x64\runner\Release
      - name: Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: BeatCinema.zip
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}